import Navbar from "./navbar";
import { FC, ReactNode } from "react";
import Head from "next/head";

interface ComponnetProps {
  children?: ReactNode;
}

const Layout: FC<ComponnetProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>سامانه  </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="main-style">{children}</main>
    </>
  );
};

export default Layout;
